import { cardCondition, cardSize, looksAutoGeneratedHandle, parseCards, parseReputation, restoreDecimal, type RawAnchor } from "../core/stores/carousell.js";
import { describe, eq } from "./harness.js";

/**
 * Reading a Carousell search page.
 *
 * ⚠️ **Every bug this suite pins was found live on 2026-08-09, and every one of them is
 * SILENT.** Three of the four make a listing look cheaper than it is, which is the
 * direction this project keeps having to design against; the fourth makes the whole shop
 * look empty. None produces an error.
 *
 * The fixtures are real anchors, copied verbatim from a rendered whey search — including
 * the missing lowercase `s`, which is not a typo in this file.
 */
describe("carousell — reading the search page");

/**
 * ⚠️ The rendered text is missing every lowercase `s`. "Used" arrives as "U ed",
 * "MuscleTech" as "Mu cleTech". A condition filter written the obvious way can never fire.
 */
eq("a second-hand badge is read despite the missing s", cardCondition("Buyer Protection Foo S$78 U ed Free delivery"), "used");
eq("a plain 'Used' is still read", cardCondition("Foo S$78 Used"), "used");
eq("a new badge is read", cardCondition("Buyer Protection Foo S$61 New"), "new");
eq("no badge is not a guess", cardCondition("Buyer Protection Foo S$61"), "unknown");

/**
 * ⚠️ Several anchors share one listing href — the card and a "Buyer Protection" badge.
 * A first-wins dedupe kept the badge, so the price came back null on every card and the
 * search returned NOTHING. Text has to be accumulated per href.
 */
const anchors: RawAnchor[] = [
	{ href: "/p/whey-protein-5lb-quality-protein-powder-1454603747/?t-id=x", text: "Buyer Protection" },
	{ href: "/p/whey-protein-5lb-quality-protein-powder-1454603747/?t-id=x", text: "Whey protein 5LB quality protein powder S$61 New" },
];
const cards = parseCards(anchors);
eq("anchors sharing an href collapse to one card", cards.length, 1);
eq("and the price survives the badge anchor", cards[0].price, 61);
eq("the title comes from the slug, not the mangled text", cards[0].title, "whey protein 5lb quality protein powder");
eq("the tracking query string is stripped", cards[0].href, "/p/whey-protein-5lb-quality-protein-powder-1454603747/");

// A link that is not a listing (no trailing numeric id) is not a card.
eq("a non-listing link is skipped", parseCards([{ href: "/p/not-a-listing/", text: "x" }]).length, 0);

describe("carousell — the size, and the decimal point the slug destroys");

/**
 * ⚠️⚠️ **The slug replaces `.` with `-`, so "2.5kg" arrives as "2 5kg" and reads as
 * FIVE kilograms.** Live example: "myprotein impact whey protein 2 5kg 83 servings" is a
 * 2.5 kg tub. Taken off the slug it doubles the pack size and halves the apparent price
 * per kg — a bargain that isn't there. The rendered text keeps the decimal, so it is
 * tried first; the slug is refused whenever this shape appears.
 */
eq(
	"the decimal survives via the rendered text",
	(cardSize({
		title: "myprotein impact whey protein 2 5kg 83 servings chocolate mint",
		text: "Buyer Protection MyProtein Impact Whey Protein 2.5KG 83 Serving S$100 New",
	}) as any).grams,
	2500,
);
eq(
	"and an ambiguous slug is REFUSED rather than doubled",
	cardSize({ title: "myprotein impact whey protein 2 5kg 83 servings", text: "" }).ok,
	false,
);
eq(
	"a whole-number slug is still usable",
	(cardSize({ title: "optimum nutrition gold standard 100 whey protein 5 lbs", text: "" }) as any).grams,
	2267.96,
);

// The price and the badges are not part of the size. "S$100" must never read as a size,
// and the `$` guard in marketplaceSize is what stops it.
eq(
	"the price is not mistaken for a size",
	(cardSize({ title: "whey protein 5lb quality protein powder", text: "Buyer Protection Whey protein 5LB quality protein powder S$61 New" }) as any).grams,
	2267.96,
);

describe("carousell — reading the seller's record");

/**
 * ⚠️⚠️ **"No review yet" is a STATED zero, not a failed read**, and merging the two cost a
 * whole diagnosis on 2026-08-09. A run of listings came back with nothing and was written
 * up as flaky rendering; the block had rendered perfectly and said `N/A — No review yet`.
 * That is not a missing signal, it is the strongest one on the page — a brand-new account
 * listing a branded product at half price — and it was being discarded as "unknown".
 */
eq(
	"a seller with no history reads as ZERO reviews, not unknown",
	parseReputation("Alan Chsi Profile detail N/A No review yet 4 month on Carou ell").reviews,
	0,
);
eq(
	"and their account age is captured, because new is itself a warning",
	parseReputation("N/A No review yet 4 month on Carou ell").ageMonths,
	4,
);
eq(
	"an established seller reads normally",
	parseReputation("Meet the eller @gheord Profile detail 5.0 (173) 173 review 12 year on Carou ell").rating,
	5,
);
eq(
	"with their review count",
	parseReputation("5.0 (173) 173 review 12 year on Carou ell").reviews,
	173,
);
eq("and years converted to months", parseReputation("5.0 (173) 12 year on Carou ell").ageMonths, 144);

// Nothing readable at all stays null — distinct from a stated zero above.
eq("an empty page is unknown, not zero", parseReputation("").reviews, null);

describe("carousell — the seller's handle");

/**
 * ⚠️ **Free evidence, and on the sample the cleanest signal of the lot.** Of six Gold
 * Standard sellers inspected 2026-08-09, the two in the plausible $85–$88 band had CHOSEN
 * names with 755 and 173 reviews over 12–13 years. All four suspiciously cheap listings
 * came from three accounts carrying Carousell's default `word` + separator + hex handle,
 * with no reviews and a few months of age. The username is in the listing's plain HTML,
 * so this costs no browser — it can rule a listing out before the expensive check runs.
 */
eq("a default underscore handle is spotted", looksAutoGeneratedHandle("liveriver_96a30c"), true);
eq("and a default dotted one", looksAutoGeneratedHandle("nobleowl.3c9a58"), true);
eq("and a longer stem", looksAutoGeneratedHandle("silentstorm_4bb81d"), true);

// The two established sellers, who must not be flagged.
eq("a chosen multi-word name is not", looksAutoGeneratedHandle("sarah.toys.store"), false);
eq("a plain chosen name is not", looksAutoGeneratedHandle("gheord"), false);
eq("nor another", looksAutoGeneratedHandle("hananinyte"), false);

/**
 * ⚠️ The two-digit rule. Hex is mostly letters, so a chosen name can be accidentally
 * hex-legible — "beaded" is six valid hex characters. Requiring digits keeps a real
 * person's handle out of the trap.
 */
eq("a hex-legible word is NOT a generated handle", looksAutoGeneratedHandle("john.beaded"), false);
eq("one digit is not enough either", looksAutoGeneratedHandle("john.bead3d"), false);
eq("missing entirely is not a match", looksAutoGeneratedHandle(undefined), false);

describe("carousell — the name recorded against the price");

/**
 * ⚠️ `item Name [Vendor n]` is there so a price can be checked against the shelf later,
 * so a name reading "2 5kg" reintroduces by eye the exact ambiguity the size parser was
 * fixed to avoid. The decimal is restored ONLY when it agrees with the size already
 * parsed from the rendered text — never invented.
 */
eq(
	"the decimal is restored once the size confirms it",
	restoreDecimal("2 5kg myprotein impact whey protein chocolate smooth", 2500),
	"2.5kg myprotein impact whey protein chocolate smooth",
);
eq("and again mid-title", restoreDecimal("titan whey protein 2 1kg 70 serving", 2100), "titan whey protein 2.1kg 70 serving");
eq(
	"a reading that disagrees with the size is LEFT ALONE",
	restoreDecimal("2 5kg myprotein impact whey protein", 5000),
	"2 5kg myprotein impact whey protein",
);
eq("a title with no ambiguity is untouched", restoreDecimal("optimum nutrition 5 lbs whey", 2267.96), "optimum nutrition 5 lbs whey");

// The existing multi-size rejection still applies through this path — one price against
// two sizes is unknowable, not a 450 g bargain.
eq(
	"two sizes in one listing are still rejected",
	cardSize({ title: "applied nutrition critical whey protein 450g 825g", text: "Applied Nutrition Critical Whey Protein 450g/825g S$30 New" }).ok,
	false,
);
