import "dotenv/config";
import { describeSlotDecision, recordVendorPrice } from "../core/ingredient-write.js";
import {
	ROUTES,
	notionClient,
	pickCandidate,
	readScanRows,
	referencePer100g,
	describeReputation,
	reputationPasses,
	REPUTATION_BAR,
	searchTermsFor,
	sizeFor,
	unitKindAgrees,
	type CandidateOutcome,
	type ScanRow,
	type VendorRoute,
} from "../core/vendor-scan.js";
import { pricePer1000 } from "../core/vendor-slots.js";
import { looksAutoGeneratedHandle, sellerReputation, type SellerReputation } from "../core/stores/carousell.js";
import type { StoreProduct } from "../core/stores/types.js";

/**
 * Fill the price book from the shops each Ingredients row already names.
 *
 *   npm run vendor-scan                          # report only — writes NOTHING
 *   npm run vendor-scan -- --only guardian
 *   npm run vendor-scan -- --write               # actually record the prices
 *
 * ⚠️ **Report-only by default, and that is the whole safety posture.** Every other
 * writer in this project is a button someone pressed while looking at one product; this
 * one goes and looks by itself, so `--write` is a separate, deliberate act. The report
 * shows exactly what would be written, including the slot decision, so the first real
 * run is reviewed rather than discovered afterwards.
 *
 * What it will never do, whatever the flags (see `recordVendorPrice`): claim a free
 * slot, evict a shop the user recorded, or touch anything outside the four columns of
 * the slot that already names this shop.
 */

const argv = process.argv.slice(2);
const flag = (name: string): string | undefined => {
	const i = argv.indexOf(`--${name}`);
	return i >= 0 ? argv[i + 1] : undefined;
};
const doWrite = argv.includes("--write");
const only = (flag("only") ?? "").toLowerCase().split(",").filter(Boolean);
const wanted = (r: VendorRoute) => !only.length || only.some((o) => r.option.toLowerCase().replace(/\s+/g, "").includes(o.replace(/\s+/g, "")));

const money = (n: number) => `$${n.toFixed(2)}`;
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Politeness between one shop's searches. */
const BETWEEN_SEARCHES_MS = 800;

/** How many under-floor listings may be checked for reputation. Each costs a browser. */
const MAX_REPUTATION_CHECKS = 3;

function slotLabel(row: ScanRow, n: number): string {
	const s = row.slots.find((x) => x.n === n)!;
	const per = pricePer1000(s.priceValue, s.sizeValue);
	if (s.priceValue == null && s.sizeValue == null && !s.urlValue && !s.itemNameValue) return "empty";
	return (
		`${s.priceValue != null ? money(s.priceValue) : "—"} / ${s.sizeValue ?? "—"}` +
		(per != null ? ` (${money(per)}/kg)` : "") +
		(s.itemNameValue ? ` "${s.itemNameValue.slice(0, 40)}"` : "")
	);
}

async function main(): Promise<void> {
	const routes = ROUTES.filter(wanted);
	console.log(
		`\nVendor scan — ${routes.map((r) => r.option).join(", ")}` +
			`\n${doWrite ? "⚠️  --write: prices WILL be recorded in Notion." : "Report only — nothing will be written."}\n` +
			"─".repeat(78),
	);

	const client = notionClient();
	const { rows, skipped } = await readScanRows(client, routes);

	// The census, printed every run. A shop whose rows have all been retagged away is
	// the difference between "found nothing" and "was never asked", and those look
	// identical in a result list.
	console.log(`\n${rows.length} row(s) name a shop in scope. Tagged slots by shop:`);
	for (const r of routes) {
		const n = rows.filter((row) => row.routes.some((m) => m.route.option === r.option)).length;
		console.log(`   ${r.option.padEnd(12)} ${String(n).padStart(3)} row(s)${n ? "" : "  ← nothing tagged; nothing to do"}`);
	}
	if (skipped.length) console.log(`   (${skipped.length} row(s) skipped: suppression tags)`);

	let found = 0;
	let written = 0;
	let refused = 0;

	for (const row of rows) {
		console.log(`\n${"─".repeat(78)}\n${row.name}   [${row.unitType}]`);
		const terms = searchTermsFor(row.target);

		for (const [i, { route, slot }] of row.routes.entries()) {
			if (i) await sleep(BETWEEN_SEARCHES_MS);
			console.log(`\n  ${route.option}  (Vendor ${slot.n}, currently: ${slotLabel(row, slot.n)})`);

			// Each term is tried only when the one before it produced no candidate, so
			// the common case is still a single request.
			let outcome = null;
			let failed = false;
			for (const [t, term] of terms.entries()) {
				if (t) await sleep(BETWEEN_SEARCHES_MS);
				let products;
				try {
					products = await route.module.search(term);
				} catch (e) {
					console.log(`    search "${term}" — ✗ failed: ${(e as Error).message}`);
					failed = true;
					break;
				}
				outcome = pickCandidate(row.target, products, {
					marketplace: route.marketplace,
					// A price already recorded at ANOTHER shop for this row — the one check
					// a search full of counterfeits cannot talk its way past.
					reference: referencePer100g(row.slots, slot.n),
				});
				console.log(
					`    search "${term}" — ${outcome.ok ? "match" : `no candidate (${outcome.reason})`}`,
				);
				if (outcome.ok) break;
			}
			if (failed) continue;

			// ⚠️ **The reputation rescue.** A listing under the price floor is a question,
			// not a verdict: an established seller with a long clean record answers it.
			// Only under-floor candidates are checked, cheapest first, because each check
			// costs a full browser render — and only until one passes.
			let rescued: { product: StoreProduct; rep: SellerReputation } | null = null;
			const under = outcome?.belowFloor ?? [];
			if (route.marketplace && under.length) {
				const cheaperThanPick = outcome?.ok
					? under.filter((u) => u.pricePer100g! < outcome.per100)
					: under;
				for (const cand of cheaperThanPick.slice(0, MAX_REPUTATION_CHECKS)) {
					// ⚠️ The FREE check first, and it usually settles it. A default
					// `word_hex` handle means the account was never personalised; paired
					// with a price already under the floor that is the throwaway-account
					// shape, and ruling it out here saves the browser render below.
					if (looksAutoGeneratedHandle(cand.seller)) {
						console.log(
							`    ✗ under the price floor, and "${cand.seller}" is an auto-generated ` +
								`handle (a never-personalised account) — skipped without a lookup`,
						);
						continue;
					}
					const rep = await sellerReputation(cand.url);
					const shown = describeReputation(rep);
					if (reputationPasses(rep)) {
						console.log(`    ↑ under the price floor, but the seller clears the bar (${shown}) — allowed`);
						rescued = { product: cand, rep };
						break;
					}
					console.log(
						`    ✗ under the price floor and the seller does not clear ` +
							`${REPUTATION_BAR.rating}★ / ${REPUTATION_BAR.reviews} reviews (${shown}) — skipped`,
					);
				}
			}

			if (!rescued && (!outcome || !outcome.ok)) {
				console.log(`    — nothing usable after ${terms.length} search term(s).`);
				continue;
			}

			const p = rescued ? rescued.product : (outcome as Extract<CandidateOutcome, { ok: true }>).product;
			if (!unitKindAgrees(row.unitType, p)) {
				// Refused rather than coerced — see `unitKindAgrees`.
				console.log(
					`    — refused: "${p.name}" is measured by ${p.unitCount ? "the piece" : "weight"}, ` +
						`but this row is ${row.unitType}. A scan may not change \`Unit type \`.`,
				);
				refused++;
				continue;
			}

			const size = sizeFor(row.unitType, p);
			const per100 = p.pricePer100g!;
			found++;
			console.log(
				`    ✓ ${money(p.priceSgd)} / ${size}${row.unitType === "By Unit" ? " pcs" : p.volumetric ? "ml" : "g"}` +
					`  =  ${money(per100 * 10)}/kg` +
					`\n      ${p.name}` +
					`\n      ${p.url}` +
					(p.seller ? `\n      seller: ${p.seller}` : "") +
					// Shown even on an above-floor pick: a normal price from a
					// never-personalised account is not a refusal, but it is worth a look
					// before you hand over money.
					(looksAutoGeneratedHandle(p.seller)
						? `  ⚠️  auto-generated handle — account never personalised`
						: "") +
					(rescued
						? `\n      ⚠️  under the price floor — allowed on seller reputation ` +
							`(${rescued.rep.rating}★, ${rescued.rep.reviews} reviews). Reviews are not ` +
							`product-specific; they say the deal completes, not that the goods are genuine.`
						: "") +
					(!rescued && outcome?.ok && outcome.rejected.length
						? `\n      ⚠️  ${outcome.rejected.length} cheaper listing(s) rejected as implausible` +
							` (the minimum on a marketplace is usually the scam)`
						: "") +
					(outcome?.ok ? `\n      (best of ${outcome.considered} matching)` : ""),
			);

			if (!doWrite) {
				console.log(`      → would record into ${slot.vendor}. Re-run with --write.`);
				continue;
			}

			try {
				const res = await recordVendorPrice(client, row.pageId, {
					vendor: route.option,
					priceSgd: p.priceSgd,
					size,
					url: p.url,
					itemName: p.name,
				});
				const landed = res.slot != null && res.slot.kind !== "none";
				// ⚠️ The test is the SLOT decision, never "were any properties sent" — a
				// button that reports a write it did not make is worse than one that fails
				// loudly (live bug, 2026-08-09).
				if (landed) {
					written++;
					console.log(`      ✔ written — ${res.written.join(", ")}`);
				} else {
					refused++;
					console.log(`      ✗ not written — ${describeSlotDecision(res.slot)}`);
				}
			} catch (e) {
				// One row's failure must not end the batch.
				refused++;
				console.log(`      ✗ write failed — ${(e as Error).message}`);
			}
		}
	}

	console.log(
		`\n${"─".repeat(78)}\n` +
			`${found} candidate(s) found` +
			(doWrite ? `, ${written} written, ${refused} refused/failed.` : `. Nothing was written (no --write).`) +
			"\n",
	);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
