import "dotenv/config";
import { describeSlotDecision, recordVendorPrice } from "../core/ingredient-write.js";
import {
	ROUTES,
	notionClient,
	pickCandidate,
	readScanRows,
	referencePer100g,
	describeReputation,
	reputationPasses,
	REPUTATION_BAR,
	searchTermsFor,
	sizeFor,
	unitKindAgrees,
	withinSizeFloor,
	type CandidateOutcome,
	type ScanRow,
	type VendorRoute,
} from "../core/vendor-scan.js";
import { packWeightOf } from "../core/notion.js";
import { PIECES_PER_QUOTE } from "../core/list-intake.js";
import { looksAutoGeneratedHandle, sellerReputation, type SellerReputation } from "../core/stores/carousell.js";
import { readVendorReview, writeVendorReview } from "../core/vendor-review-file.js";
import {
	findPendingFor,
	isRejectedPick,
	renderReviewSummary,
	reviewReasons,
	reviewToken,
	prunePending,
	sizeBoundsFor,
	withPending,
	type PendingReview,
	type ReviewReason,
} from "../core/vendor-review.js";
import { cooldownKey } from "../core/cooldown.js";
import { renderReviewPage } from "../core/review-page.js";
import { sendHtml } from "../core/telegram.js";
import { config } from "../core/config.js";
import { commitAndPushData } from "../core/git-data-push.js";
import { mkdir, writeFile } from "node:fs/promises";

/** Where the review page is written. Built into `public/` like every other page. */
const REVIEW_PAGE_PATH = "public/review.html";
import type { StoreProduct } from "../core/stores/types.js";

/**
 * Fill the price book from the shops each Ingredients row already names.
 *
 *   npm run vendor-scan                          # report only — writes NOTHING
 *   npm run vendor-scan -- --only guardian
 *   npm run vendor-scan -- --write               # record the clear ones, ASK about the rest
 *   npm run vendor-scan -- --write --no-ask      # record the clear ones, queue the rest silently
 *   npm run vendor-scan -- --write --no-push     # queue locally; don't update the live page
 *
 * ⚠️ **Report-only by default, and that is the whole safety posture.** Every other
 * writer in this project is a button someone pressed while looking at one product; this
 * one goes and looks by itself, so `--write` is a separate, deliberate act. The report
 * shows exactly what would be written, including the slot decision, so the first real
 * run is reviewed rather than discovered afterwards.
 *
 * What it will never do, whatever the flags (see `recordVendorPrice`): claim a free
 * slot, evict a shop the user recorded, or touch anything outside the four columns of
 * the slot that already names this shop.
 *
 * ⚠️ **`--write` no longer means "write everything it found".** A pick the scan is
 * uneasy about — a catering pack, a size read off a range, a marketplace rescue — is
 * queued and asked about over Telegram instead (`vendor-review.ts`). This exists because
 * the first NTUC/Sheng Siong report would otherwise have filed a **10 kg sack of
 * carrots** and a **12 × 1 L case of milk** as the recorded price for those rows: both
 * genuinely the cheapest per kilo, neither a pack anyone buys.
 */

const argv = process.argv.slice(2);
const flag = (name: string): string | undefined => {
	const i = argv.indexOf(`--${name}`);
	return i >= 0 ? argv[i + 1] : undefined;
};
const doWrite = argv.includes("--write");
/** Queue the uncertain picks but send no Telegram message — for an unattended run. */
const noAsk = argv.includes("--no-ask");
/** Write the queue locally but don't commit it — the live review page stays as it was. */
const noPush = argv.includes("--no-push");
const only = (flag("only") ?? "").toLowerCase().split(",").filter(Boolean);
const wanted = (r: VendorRoute) => !only.length || only.some((o) => r.option.toLowerCase().replace(/\s+/g, "").includes(o.replace(/\s+/g, "")));

const money = (n: number) => `$${n.toFixed(2)}`;
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Politeness between one shop's searches. */
const BETWEEN_SEARCHES_MS = 800;

/** How many under-floor listings may be checked for reputation. Each costs a browser. */
const MAX_REPUTATION_CHECKS = 3;

/** What `Size[Vendor n]` counts on this row — the word after the number. */
function unitWord(row: ScanRow): string {
	return row.unitType === "By Unit" ? " pcs" : row.unitType === "By ml" ? "ml" : "g";
}

/**
 * A price and a pack, expressed in whatever dimension the ROW is actually priced in.
 *
 * ⚠️ **The old code printed `/kg` unconditionally**, which on a `By Unit` row is the
 * price of a *thousand eggs* wearing a per-kilo label — `$399.00/kg` for a $3.99 box of
 * ten. This is report-only text and writes nothing, but it is the number a human reads
 * while deciding whether the scan is behaving, so it follows the same rule as everything
 * else: `packWeightOf` decides whether there is a weight to divide by, and a counted pack
 * with no stated weight quotes **per piece** instead — the figure you use at the shelf
 * between a box of 10 and a box of 30. See `docs/session-2026-08-11-price-per-kg.md`.
 */
function perLabel(row: ScanRow, price: number | null, size: number | null, itemName: string): string {
	if (price == null || price <= 0) return "";
	const grams = packWeightOf(row.unitType, size, row.name, itemName);
	if (grams != null && grams > 0) return `${money((price / grams) * 1000)}/${row.unitType === "By ml" ? "L" : "kg"}`;
	// ⚠️ **Per TEN pieces, not per one** — `PIECES_PER_QUOTE`, mirroring Notion's own
	// `Cheapest Price/Kg ` formula (`4.2 /10 pc`). Two conventions for one figure, living
	// in two databases, is exactly where someone later assumes a factor of ten. This line
	// quoted `$0.400/pc` when it was written, which is the same number scaled — and the
	// wrong one to print beside a column that says `/10 pc`.
	if (row.unitType === "By Unit" && size != null && size > 0) {
		return `$${((price / size) * PIECES_PER_QUOTE).toFixed(2)}/${PIECES_PER_QUOTE} pc`;
	}
	return "";
}

function slotLabel(row: ScanRow, n: number): string {
	const s = row.slots.find((x) => x.n === n)!;
	if (s.priceValue == null && s.sizeValue == null && !s.urlValue && !s.itemNameValue) {
		// ⚠️ "empty" describes the four DATA columns, not the slot: `Vendor n` still
		// names this shop, which is the whole reason the row is being scanned and the
		// reason a write here is an `update` rather than a refused `fill`.
		return "tagged, no price yet";
	}
	const per = perLabel(row, s.priceValue, s.sizeValue, s.itemNameValue);
	return (
		`${s.priceValue != null ? money(s.priceValue) : "—"} / ${s.sizeValue ?? "—"}${unitWord(row)}` +
		(per ? ` (${per})` : "") +
		(s.itemNameValue ? ` "${s.itemNameValue.slice(0, 40)}"` : "")
	);
}

async function main(): Promise<void> {
	const routes = ROUTES.filter(wanted);
	console.log(
		`\nVendor scan — ${routes.map((r) => r.option).join(", ")}` +
			`\n${doWrite ? "⚠️  --write: prices WILL be recorded in Notion." : "Report only — nothing will be written."}\n` +
			"─".repeat(78),
	);

	const client = notionClient();
	// Read once for the whole pass: standing "Don't use" decisions, plus any questions
	// still outstanding from a previous run (pruned of anything too old to answer).
	let review = prunePending(await readVendorReview());
	const { rows, skipped } = await readScanRows(client, routes);

	// The census, printed every run. A shop whose rows have all been retagged away is
	// the difference between "found nothing" and "was never asked", and those look
	// identical in a result list.
	console.log(`\n${rows.length} row(s) name a shop in scope. Tagged slots by shop:`);
	for (const r of routes) {
		const n = rows.filter((row) => row.routes.some((m) => m.route.option === r.option)).length;
		console.log(`   ${r.option.padEnd(12)} ${String(n).padStart(3)} row(s)${n ? "" : "  ← nothing tagged; nothing to do"}`);
	}
	if (skipped.length) console.log(`   (${skipped.length} row(s) skipped: suppression tags)`);

	let found = 0;
	let written = 0;
	let refused = 0;
	let skippedByUser = 0;
	/** Candidates dropped by the row's own `Size - floor (g/ml)` ceiling. */
	let skippedOverFloor = 0;
	/** Uncertain picks, queued for the Telegram ask at the end of the pass. */
	const toAsk: PendingReview[] = [];

	for (const row of rows) {
		console.log(
			`\n${"─".repeat(78)}\n${row.name}   [${row.unitType}]` +
				(row.sizeFloor != null ? `   ≤ ${row.sizeFloor}${unitWord(row)}` : ""),
		);
		const terms = searchTermsFor(row.target);

		for (const [i, { route, slot }] of row.routes.entries()) {
			if (i) await sleep(BETWEEN_SEARCHES_MS);
			console.log(`\n  ${route.option}  (Vendor ${slot.n}, currently: ${slotLabel(row, slot.n)})`);

			// Each term is tried only when the one before it produced no candidate, so
			// the common case is still a single request.
			let outcome = null;
			let failed = false;
			for (const [t, term] of terms.entries()) {
				if (t) await sleep(BETWEEN_SEARCHES_MS);
				let products;
				try {
					products = await route.module.search(term);
				} catch (e) {
					console.log(`    search "${term}" — ✗ failed: ${(e as Error).message}`);
					failed = true;
					break;
				}
				// ⚠️ Standing "Don't use" answers are applied BEFORE the pick, not after, so
				// the scan goes on to offer the next-best pack rather than reporting the
				// refused one and giving up. Refusing the 5 L soy sauce should surface the
				// 640 ml bottle, not silence the row.
				//
				// ⚠️ Size bounds are applied here too, and they are the difference between a
				// refusal that skips one URL and one that answers the question. Excluding
				// only the 10 kg sack promotes the 5 kg sack, and the user gets asked again
				// next week in a smaller size; a ceiling ends it. See `sizeBoundsFor`.
				const bounds = sizeBoundsFor(review, row.pageId, route.option);
				const before = products.length;
				let overFloor = 0;
				products = products.filter((p) => {
					if (isRejectedPick(review, row.pageId, route.option, p)) return false;
					// ⚠️ The row's own declared ceiling, checked FIRST and in the row's own
					// units — see `withinSizeFloor`. This is the standing version of the
					// "Pack too large" button: `sizeBoundsFor` below is what the user taught
					// the scan one refusal at a time, and `Size - floor (g/ml)` is them
					// saying it up front for every shop at once.
					if (!withinSizeFloor(row.sizeFloor, sizeFor(row.unitType, p))) {
						overFloor++;
						return false;
					}
					const g = packWeightOf(row.unitType, sizeFor(row.unitType, p), row.name, p.name);
					if (g == null) return true; // no weight is no opinion, as everywhere else
					if (bounds.maxGrams != null && g >= bounds.maxGrams) return false;
					if (bounds.minGrams != null && g <= bounds.minGrams) return false;
					return true;
				});
				if (products.length < before) skippedByUser += before - products.length - overFloor;
				if (overFloor) {
					skippedOverFloor += overFloor;
					// Printed per search, because "no candidate" and "no candidate under
					// your ceiling" are different problems and only one of them is the
					// ceiling being set too tight.
					console.log(`    (${overFloor} over this row's ${row.sizeFloor}${unitWord(row)} size ceiling)`);
				}
				outcome = pickCandidate(row.target, products, {
					marketplace: route.marketplace,
					// A price already recorded at ANOTHER shop for this row — the one check
					// a search full of counterfeits cannot talk its way past.
					reference: referencePer100g(row.slots, slot.n, row),
				});
				console.log(
					`    search "${term}" — ${outcome.ok ? "match" : `no candidate (${outcome.reason})`}`,
				);
				if (outcome.ok) break;
			}
			if (failed) continue;

			// ⚠️ **The reputation rescue.** A listing under the price floor is a question,
			// not a verdict: an established seller with a long clean record answers it.
			// Only under-floor candidates are checked, cheapest first, because each check
			// costs a full browser render — and only until one passes.
			let rescued: { product: StoreProduct; rep: SellerReputation } | null = null;
			const under = outcome?.belowFloor ?? [];
			if (route.marketplace && under.length) {
				const cheaperThanPick = outcome?.ok
					? under.filter((u) => u.pricePer100g! < outcome.per100)
					: under;
				for (const cand of cheaperThanPick.slice(0, MAX_REPUTATION_CHECKS)) {
					// ⚠️ The FREE check first, and it usually settles it. A default
					// `word_hex` handle means the account was never personalised; paired
					// with a price already under the floor that is the throwaway-account
					// shape, and ruling it out here saves the browser render below.
					if (looksAutoGeneratedHandle(cand.seller)) {
						console.log(
							`    ✗ under the price floor, and "${cand.seller}" is an auto-generated ` +
								`handle (a never-personalised account) — skipped without a lookup`,
						);
						continue;
					}
					const rep = await sellerReputation(cand.url);
					const shown = describeReputation(rep);
					if (reputationPasses(rep)) {
						console.log(`    ↑ under the price floor, but the seller clears the bar (${shown}) — allowed`);
						rescued = { product: cand, rep };
						break;
					}
					console.log(
						`    ✗ under the price floor and the seller does not clear ` +
							`${REPUTATION_BAR.rating}★ / ${REPUTATION_BAR.reviews} reviews (${shown}) — skipped`,
					);
				}
			}

			if (!rescued && (!outcome || !outcome.ok)) {
				console.log(`    — nothing usable after ${terms.length} search term(s).`);
				continue;
			}

			const p = rescued ? rescued.product : (outcome as Extract<CandidateOutcome, { ok: true }>).product;
			if (!unitKindAgrees(row.unitType, p)) {
				// Refused rather than coerced — see `unitKindAgrees`.
				console.log(
					`    — refused: "${p.name}" is measured by ${p.unitCount ? "the piece" : "weight"}, ` +
						`but this row is ${row.unitType}. A scan may not change \`Unit type \`.`,
				);
				refused++;
				continue;
			}

			const size = sizeFor(row.unitType, p);
			found++;
			// ⚠️ Quoted through `perLabel`, i.e. from what will actually be STORED
			// (`Price [Vendor n]` and `Size[Vendor n]`), not from the product's own
			// `pricePer100g`. On a By-Unit row those two disagree — the slot holds a
			// count — and the report should show the figure Notion will show.
			const per = perLabel(row, p.priceSgd, size, p.name);
			console.log(
				`    ✓ ${money(p.priceSgd)} / ${size}${unitWord(row)}` +
					(per ? `  =  ${per}` : "") +
					`\n      ${p.name}` +
					`\n      ${p.url}` +
					(p.seller ? `\n      seller: ${p.seller}` : "") +
					// Shown even on an above-floor pick: a normal price from a
					// never-personalised account is not a refusal, but it is worth a look
					// before you hand over money.
					(looksAutoGeneratedHandle(p.seller)
						? `  ⚠️  auto-generated handle — account never personalised`
						: "") +
					(rescued
						? `\n      ⚠️  under the price floor — allowed on seller reputation ` +
							`(${rescued.rep.rating}★, ${rescued.rep.reviews} reviews). Reviews are not ` +
							`product-specific; they say the deal completes, not that the goods are genuine.`
						: "") +
					(!rescued && outcome?.ok && outcome.rejected.length
						? `\n      ⚠️  ${outcome.rejected.length} cheaper listing(s) rejected as implausible` +
							` (the minimum on a marketplace is usually the scam)`
						: "") +
					(outcome?.ok ? `\n      (best of ${outcome.considered} matching)` : ""),
			);

			// ⚠️ **The uncertainty gate, and it sits BEFORE the write on purpose.** Every
			// pick above this line has already passed the matcher and the price rules; the
			// question here is a different one — *is this the pack you would actually
			// buy?* — and it is not one a scan can answer. See `vendor-review.ts`.
			const reasons: ReviewReason[] = reviewReasons(p, {
				packGrams: packWeightOf(row.unitType, size, row.name, p.name),
				// ⚠️ A pack inside a ceiling the user typed themselves is not a pack to ask
				// them about. Without this the three whey rows (ceiling 10 kg, real packs
				// 2.5 kg) would clear the filter and then be queued anyway by `BULK_GRAMS`,
				// which is 2 kg — asking a question already answered in Notion, every run.
				sizeFloorOk: row.sizeFloor != null && withinSizeFloor(row.sizeFloor, size),
				referencePer100g: referencePer100g(row.slots, slot.n, row),
				rescued: !!rescued,
				rejectedCheaper: !rescued && outcome?.ok ? outcome.rejected.length : 0,
				autoHandle: looksAutoGeneratedHandle(p.seller),
			});

			if (reasons.length) {
				// Already asked and still waiting? Say nothing — see `findPendingFor`.
				const outstanding = findPendingFor(review, row.pageId, route.option, p);
				if (outstanding?.messageId) {
					console.log(`      ？ already asked on Telegram — still waiting on your answer.`);
					continue;
				}
				const pending: PendingReview = {
					token: outstanding?.token ?? reviewToken(review),
					ingredientId: row.pageId,
					ingredientName: row.name,
					key: cooldownKey(row.target.search.searchTerm),
					unitType: row.unitType,
					vendor: route.option,
					slotN: slot.n,
					// From `parseName`, so the page offers "Wrong brand" only where a
					// bracketed brand actually exists to enforce.
					brand: row.target.search.brand || undefined,
					priceSgd: p.priceSgd,
					size: size!,
					url: p.url,
					itemName: p.name,
					perLabel: per,
					reasons,
					askedAt: new Date().toISOString(),
				};
				// Queued into the live file immediately so the token it holds is reserved
				// against the next `reviewToken` call in this same loop.
				review = withPending(review, pending);
				toAsk.push(pending);
				console.log(
					`      ？ not written — asking you first:\n` +
						reasons.map((r) => `        ⚠️  ${r.note}`).join("\n"),
				);
				continue;
			}

			if (!doWrite) {
				console.log(`      → would record into ${slot.vendor}. Re-run with --write.`);
				continue;
			}

			try {
				const res = await recordVendorPrice(client, row.pageId, {
					vendor: route.option,
					priceSgd: p.priceSgd,
					size,
					url: p.url,
					itemName: p.name,
				});
				const landed = res.slot != null && res.slot.kind !== "none";
				// ⚠️ The test is the SLOT decision, never "were any properties sent" — a
				// button that reports a write it did not make is worse than one that fails
				// loudly (live bug, 2026-08-09).
				if (landed) {
					written++;
					console.log(`      ✔ written — ${res.written.join(", ")}`);
				} else {
					refused++;
					console.log(`      ✗ not written — ${describeSlotDecision(res.slot)}`);
				}
			} catch (e) {
				// One row's failure must not end the batch.
				refused++;
				console.log(`      ✗ write failed — ${(e as Error).message}`);
			}
		}
	}

	await askAboutUncertain(toAsk, review, written);

	console.log(
		`\n${"─".repeat(78)}\n` +
			`${found} candidate(s) found` +
			(doWrite ? `, ${written} written, ${refused} refused/failed` : `, nothing written (no --write)`) +
			(toAsk.length ? `, ${toAsk.length} awaiting your call` : "") +
			(skippedByUser ? `, ${skippedByUser} listing(s) skipped as previously refused` : "") +
			(skippedOverFloor ? `, ${skippedOverFloor} over a row's size ceiling` : "") +
			".\n",
	);
}

/**
 * Send the review cards and persist the queue.
 *
 * ⚠️ **The file is written even when Telegram fails**, and that order matters. A queued
 * question with no message is recoverable — the next run re-sends it — but a message
 * whose token was never persisted is a button that answers into the void, and the user
 * has no way to tell the two apart from their phone.
 *
 * One card per pick rather than one message listing them all: an inline keyboard belongs
 * to a whole message, so a single message could only carry numbered buttons, and reading
 * "Don't use #7" against a list is exactly how the wrong thing gets refused.
 */
async function askAboutUncertain(
	toAsk: PendingReview[],
	review: Parameters<typeof writeVendorReview>[0],
	written: number,
): Promise<void> {
	// ⚠️ **A report-only run writes NOTHING — not Notion, and not this file either.**
	// It has already printed every reason to the console, which is what it was run for.
	// Persisting a queue would make `npm run vendor-scan` with no flags leave state
	// behind, and "report only" has to mean exactly what it says or it stops being the
	// safe thing to reach for.
	if (!doWrite) {
		if (toAsk.length) console.log(`\n${toAsk.length} pick(s) would be queued for your review.`);
		return;
	}

	if (!toAsk.length) {
		await writeVendorReview(review);
		return;
	}

	if (noAsk) {
		await writeVendorReview(review);
		console.log(`\n${toAsk.length} pick(s) queued for review — not sent (--no-ask).`);
		return;
	}

	// ⚠️ **One page, one message — never one message per pick.** The first live run
	// queued 16 picks and sent 16 separate cards, which is not a review queue, it is a
	// reason to mute the bot; and a muted bot loses the daily digest with it. The rest of
	// this project has always been "one Telegram message → one page", and so is this.
	await mkdir("public", { recursive: true });
	const page = renderReviewPage(review.pending, { repo: config.repo() });
	await writeFile(REVIEW_PAGE_PATH, page, "utf8");
	console.log(`\nWrote ${REVIEW_PAGE_PATH} (${review.pending.length} waiting).`);

	await writeVendorReview(review);

	// ⚠️ **The queue has to reach the CLOUD or the Telegram link is a lie.** `public/` is
	// gitignored and rebuilt by the daily workflow, so the page written above is a local
	// preview; what the phone opens is built from `data/vendor-review.json` in the repo.
	// Pushing is therefore part of asking, not a separate chore — same shape as the Sheng
	// Siong runner, and the same `commitAndPushData` that survives a rejected push.
	let published = false;
	if (noPush) {
		console.log(`(--no-push: data/vendor-review.json not committed; the live page will not change.)`);
	} else {
		try {
			await commitAndPushData({
				file: "data/vendor-review.json",
				message: `data: ${review.pending.length} price(s) awaiting review`,
			});
			published = true;
		} catch (e) {
			console.log(`⚠️  Could not push the review queue (${(e as Error).message}).`);
		}
	}

	try {
		// ⚠️ Only linked when the queue actually reached the repo. A message pointing at a
		// page that still shows yesterday's questions is worse than one that says so.
		await sendHtml(
			renderReviewSummary(toAsk.length, written, published ? config.reviewUrl() : undefined),
		);
		console.log(`📨 Sent one review link to Telegram.`);
	} catch (e) {
		console.log(`⚠️  Could not send the review link (${(e as Error).message}).`);
		console.log(`   The picks stay queued in data/vendor-review.json; the page is still written.`);
	}
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
