import "dotenv/config";
import { describeSlotDecision, recordVendorPrice } from "../core/ingredient-write.js";
import {
	ROUTES,
	notionClient,
	pickCandidate,
	readScanRows,
	referencePer100g,
	describeReputation,
	reputationPasses,
	REPUTATION_BAR,
	searchTermsFor,
	sizeFor,
	needsSizeInName,
	resolveSize,
	packWithinCeiling,
	type CandidateOutcome,
	type ScanRow,
	type PriceMove,
	renderPriceMoves,
	type VendorRoute,
} from "../core/vendor-scan.js";
import { packWeightOf } from "../core/notion.js";
import { pricePer1000 } from "../core/vendor-slots.js";
import { PIECES_PER_QUOTE } from "../core/list-intake.js";
import { looksAutoGeneratedHandle, sellerReputation, type SellerReputation } from "../core/stores/carousell.js";
import { readVendorReview, writeVendorReview } from "../core/vendor-review-file.js";
import {
	dearerThanRecorded,
	findPendingFor,
	isRejectedPick,
	renderReviewSummary,
	reviewReasons,
	reviewToken,
	prunePending,
	sizeBoundsFor,
	sizeText,
	withPending,
	withoutPendingForSlot,
	type PendingReview,
	type ReviewReason,
} from "../core/vendor-review.js";
import { cooldownKey } from "../core/cooldown.js";
import { renderReviewPage } from "../core/review-page.js";
import { escapeHtml, formatWeightGaps, sendHtml, type WeightGapNote } from "../core/telegram.js";
import { config } from "../core/config.js";
import { commitAndPushData } from "../core/git-data-push.js";
import { mkdir, writeFile } from "node:fs/promises";

/** Where the review page is written. Built into `public/` like every other page. */
const REVIEW_PAGE_PATH = "public/review.html";
import type { StoreProduct } from "../core/stores/types.js";
import { atShelfPrice } from "../core/stores/shelf-price.js";

/**
 * Fill the price book from the shops each Ingredients row already names.
 *
 *   npm run vendor-scan                          # report only — writes NOTHING
 *   npm run vendor-scan -- --only guardian
 *   npm run vendor-scan -- --write               # record the clear ones, ASK about the rest
 *   npm run vendor-scan -- --write --no-ask      # record the clear ones, queue the rest silently
 *   npm run vendor-scan -- --write --no-push     # queue locally; don't update the live page
 *
 * ⚠️ **Report-only by default, and that is the whole safety posture.** Every other
 * writer in this project is a button someone pressed while looking at one product; this
 * one goes and looks by itself, so `--write` is a separate, deliberate act. The report
 * shows exactly what would be written, including the slot decision, so the first real
 * run is reviewed rather than discovered afterwards.
 *
 * What it will never do, whatever the flags (see `recordVendorPrice`): claim a free
 * slot, evict a shop the user recorded, or touch anything outside the four columns of
 * the slot that already names this shop.
 *
 * ⚠️ **`--write` no longer means "write everything it found".** A pick the scan is
 * uneasy about — a catering pack, a size read off a range, a marketplace rescue — is
 * queued and asked about over Telegram instead (`vendor-review.ts`). This exists because
 * the first NTUC/Sheng Siong report would otherwise have filed a **10 kg sack of
 * carrots** and a **12 × 1 L case of milk** as the recorded price for those rows: both
 * genuinely the cheapest per kilo, neither a pack anyone buys.
 */

const argv = process.argv.slice(2);
const flag = (name: string): string | undefined => {
	const i = argv.indexOf(`--${name}`);
	return i >= 0 ? argv[i + 1] : undefined;
};
const doWrite = argv.includes("--write");
/**
 * Queue the uncertain picks and publish the review page, but send no Telegram QUESTION —
 * for an unattended run, where a daily "N picks need your call" is a nag.
 *
 * ⚠️ **It still records and still publishes.** Until 2026-09-01 this returned before the
 * push, which loses the whole queue on an ephemeral Actions runner. `--no-push` is the
 * flag for not committing.
 *
 * ⚠️ **It does not silence a price that MOVED.** That message only fires on a real
 * change, so it is not the daily nag this flag exists to prevent.
 */
const noAsk = argv.includes("--no-ask");
/** Write the queue locally but don't commit it — the live review page stays as it was. */
const noPush = argv.includes("--no-push");
const only = (flag("only") ?? "").toLowerCase().split(",").filter(Boolean);
const wanted = (r: VendorRoute) => !only.length || only.some((o) => r.option.toLowerCase().replace(/\s+/g, "").includes(o.replace(/\s+/g, "")));

const money = (n: number) => `$${n.toFixed(2)}`;
const round1 = (n: number) => Math.round(n * 10) / 10;
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Politeness between one shop's searches. */
const BETWEEN_SEARCHES_MS = 800;

/** How many under-floor listings may be checked for reputation. Each costs a browser. */
const MAX_REPUTATION_CHECKS = 3;

/** What `Size[Vendor n]` counts on this row — the word after the number. */
function unitWord(row: ScanRow): string {
	return row.unitType === "By Unit" ? " pcs" : row.unitType === "By ml" ? "ml" : "g";
}

/**
 * A price and a pack, expressed in whatever dimension the ROW is actually priced in.
 *
 * ⚠️ **The old code printed `/kg` unconditionally**, which on a `By Unit` row is the
 * price of a *thousand eggs* wearing a per-kilo label — `$399.00/kg` for a $3.99 box of
 * ten. This is report-only text and writes nothing, but it is the number a human reads
 * while deciding whether the scan is behaving, so it follows the same rule as everything
 * else: `packWeightOf` decides whether there is a weight to divide by, and a counted pack
 * with no stated weight quotes **per piece** instead — the figure you use at the shelf
 * between a box of 10 and a box of 30. See `docs/session-2026-08-11-price-per-kg.md`.
 */
function perLabel(row: ScanRow, price: number | null, size: number | null, itemName: string): string {
	if (price == null || price <= 0) return "";
	const grams = packWeightOf(row.unitType, size, row.name, itemName);
	if (grams != null && grams > 0) return `${money((price / grams) * 1000)}/${row.unitType === "By ml" ? "L" : "kg"}`;
	// ⚠️ **Per TEN pieces, not per one** — `PIECES_PER_QUOTE`, mirroring Notion's own
	// `Cheapest Price/Kg ` formula (`4.2 /10 pc`). Two conventions for one figure, living
	// in two databases, is exactly where someone later assumes a factor of ten. This line
	// quoted `$0.400/pc` when it was written, which is the same number scaled — and the
	// wrong one to print beside a column that says `/10 pc`.
	if (row.unitType === "By Unit" && size != null && size > 0) {
		return `$${((price / size) * PIECES_PER_QUOTE).toFixed(2)}/${PIECES_PER_QUOTE} pc`;
	}
	return "";
}

/** Exactly what the two Notion columns hold, e.g. `$2.40 / 20 pcs`. */
function priceSizeText(row: ScanRow, price: number | null, size: number | null): string {
	if (price == null || size == null) return "";
	return `${money(price)} / ${size}${unitWord(row)}`;
}

/** What `pricePer1000` means on this row, for a message that has to state its units. */
function perWord(row: ScanRow): string {
	return row.unitType === "By Unit" ? "1000 pcs" : row.unitType === "By ml" ? "L" : "kg";
}

function slotLabel(row: ScanRow, n: number): string {
	const s = row.slots.find((x) => x.n === n)!;
	if (s.priceValue == null && s.sizeValue == null && !s.urlValue && !s.itemNameValue) {
		// ⚠️ "empty" describes the four DATA columns, not the slot: `Vendor n` still
		// names this shop, which is the whole reason the row is being scanned and the
		// reason a write here is an `update` rather than a refused `fill`.
		return "tagged, no price yet";
	}
	const per = perLabel(row, s.priceValue, s.sizeValue, s.itemNameValue);
	return (
		`${s.priceValue != null ? money(s.priceValue) : "—"} / ${s.sizeValue ?? "—"}${unitWord(row)}` +
		(per ? ` (${per})` : "") +
		(s.itemNameValue ? ` "${s.itemNameValue.slice(0, 40)}"` : "")
	);
}

async function main(): Promise<void> {
	const routes = ROUTES.filter(wanted);
	console.log(
		`\nVendor scan — ${routes.map((r) => r.option).join(", ")}` +
			`\n${doWrite ? "⚠️  --write: prices WILL be recorded in Notion." : "Report only — nothing will be written."}\n` +
			"─".repeat(78),
	);

	const client = notionClient();
	// Read once for the whole pass: standing "Don't use" decisions, plus any questions
	// still outstanding from a previous run (pruned of anything too old to answer).
	let review = prunePending(await readVendorReview());
	const { rows, skipped } = await readScanRows(client, routes);

	// The census, printed every run. A shop whose rows have all been retagged away is
	// the difference between "found nothing" and "was never asked", and those look
	// identical in a result list.
	console.log(`\n${rows.length} row(s) name a shop in scope. Tagged slots by shop:`);
	for (const r of routes) {
		const n = rows.filter((row) => row.routes.some((m) => m.route.option === r.option)).length;
		console.log(`   ${r.option.padEnd(12)} ${String(n).padStart(3)} row(s)${n ? "" : "  ← nothing tagged; nothing to do"}`);
	}
	if (skipped.length) console.log(`   (${skipped.length} row(s) skipped: suppression tags)`);

	let found = 0;
	let written = 0;
	let refused = 0;
	/**
	 * Questions this run took OFF the queue by recording the price instead — not the same
	 * as an answered tap, and not counted among `written` for the Telegram summary. It
	 * exists so the publish path below knows the queue changed even when nothing new was
	 * asked, which is exactly the case that left three stale questions on the live page.
	 */
	let questionsDropped = 0;
	/** Slots whose recorded price actually moved this run — see `renderPriceMoves`. */
	const moves: PriceMove[] = [];
	/** Written, but at the price already recorded. Counted, never itemised. */
	let reconfirmed = 0;
	let skippedByUser = 0;
	/** Candidates dropped by the row's own `Size - Ceiling (g/ml)`. */
	let skippedOverCeiling = 0;
	/** Uncertain picks, queued for the Telegram ask at the end of the pass. */
	const toAsk: PendingReview[] = [];
	/** By Unit rows a shop prices by weight — fixable by typing a size into the name. */
	const gaps: WeightGapNote[] = [];

	for (const row of rows) {
		console.log(
			`\n${"─".repeat(78)}\n${row.name}   [${row.unitType}]` +
				// ⚠️ Both figures on a By Unit row, and the second is not decoration. The
				// column is labelled `(g/ml)` but a counted row bounds a COUNT, so `≤ 600`
				// on a bread row reads as 600 slices — which is what the code does with it.
				// Printing the derived weight beside it (`≈ 18kg`) is what makes a value
				// typed in the wrong dimension visible instead of silently harmless.
				(row.sizeCeiling != null ? `   ≤ ${row.sizeCeiling}${unitWord(row)}` : "") +
				(row.sizeCeiling != null && row.unitType === "By Unit" && row.ceilingGrams != null
					? ` (≈ ${sizeText(row.ceilingGrams)} by weight)`
					: ""),
		);
		const terms = searchTermsFor(row.target);

		for (const [i, { route, slot }] of row.routes.entries()) {
			if (i) await sleep(BETWEEN_SEARCHES_MS);
			console.log(`\n  ${route.option}  (Vendor ${slot.n}, currently: ${slotLabel(row, slot.n)})`);

			// Each term is tried only when the one before it produced no candidate, so
			// the common case is still a single request.
			let outcome = null;
			let failed = false;
			for (const [t, term] of terms.entries()) {
				if (t) await sleep(BETWEEN_SEARCHES_MS);
				let products;
				try {
					// ⚠️ **Pre-promo prices, applied here and not later.** Everything below —
					// the size filters, `pickCandidate`'s ranking, the review card, the write —
					// reads whatever this returns. See `atShelfPrice` for why a promo price must
					// never reach the price book, and why ranking on one picks the dearer pack.
					products = (await route.module.search(term)).map(atShelfPrice);
				} catch (e) {
					console.log(`    search "${term}" — ✗ failed: ${(e as Error).message}`);
					failed = true;
					break;
				}
				// ⚠️ Standing "Don't use" answers are applied BEFORE the pick, not after, so
				// the scan goes on to offer the next-best pack rather than reporting the
				// refused one and giving up. Refusing the 5 L soy sauce should surface the
				// 640 ml bottle, not silence the row.
				//
				// ⚠️ Size bounds are applied here too, and they are the difference between a
				// refusal that skips one URL and one that answers the question. Excluding
				// only the 10 kg sack promotes the 5 kg sack, and the user gets asked again
				// next week in a smaller size; a ceiling ends it. See `sizeBoundsFor`.
				const bounds = sizeBoundsFor(review, row.pageId, route.option);
				const before = products.length;
				let overCeiling = 0;
				products = products.filter((p) => {
					if (isRejectedPick(review, row.pageId, route.option, p)) return false;
					// ⚠️ The row's own declared ceiling, checked FIRST and in the row's own
					// units — see `withinSizeCeiling`. This is the standing version of the
					// "Pack too large" button: `sizeBoundsFor` below is what the user taught
					// the scan one refusal at a time, and `Size - Ceiling (g/ml)` is them
					// saying it up front for every shop at once.
					if (!packWithinCeiling(row, p)) {
						overCeiling++;
						return false;
					}
					const g = packWeightOf(row.unitType, sizeFor(row.unitType, p), row.name, p.name);
					if (g == null) return true; // no weight is no opinion, as everywhere else
					if (bounds.maxGrams != null && g >= bounds.maxGrams) return false;
					if (bounds.minGrams != null && g <= bounds.minGrams) return false;
					return true;
				});
				if (products.length < before) skippedByUser += before - products.length - overCeiling;
				skippedOverCeiling += overCeiling;
				outcome = pickCandidate(row.target, products, {
					marketplace: route.marketplace,
					// A price already recorded at ANOTHER shop for this row — the one check
					// a search full of counterfeits cannot talk its way past.
					reference: referencePer100g(row.slots, slot.n, row),
				});
				console.log(
					`    search "${term}" — ${outcome.ok ? "match" : `no candidate (${outcome.reason})`}` +
						// ⚠️ On the SAME line as the result it explains. "No candidate" and "no
						// candidate under your ceiling" are different problems — the second one
						// is the ceiling set too tight, and the only way to see that is to read
						// the two facts together.
						// Not re-quoting the ceiling in units here: on a By Unit row some of these
					// were dropped on the derived WEIGHT, and naming one dimension for both
					// would misreport half the count. The row header states both figures.
					(overCeiling ? ` — ${overCeiling} over this row's size ceiling` : ""),
				);
				if (outcome.ok) break;
			}
			if (failed) continue;

			// ⚠️ **The reputation rescue.** A listing under the price floor is a question,
			// not a verdict: an established seller with a long clean record answers it.
			// Only under-floor candidates are checked, cheapest first, because each check
			// costs a full browser render — and only until one passes.
			let rescued: { product: StoreProduct; rep: SellerReputation } | null = null;
			const under = outcome?.belowFloor ?? [];
			if (route.marketplace && under.length) {
				const cheaperThanPick = outcome?.ok
					? under.filter((u) => u.pricePer100g! < outcome.per100)
					: under;
				for (const cand of cheaperThanPick.slice(0, MAX_REPUTATION_CHECKS)) {
					// ⚠️ The FREE check first, and it usually settles it. A default
					// `word_hex` handle means the account was never personalised; paired
					// with a price already under the floor that is the throwaway-account
					// shape, and ruling it out here saves the browser render below.
					if (looksAutoGeneratedHandle(cand.seller)) {
						console.log(
							`    ✗ under the price floor, and "${cand.seller}" is an auto-generated ` +
								`handle (a never-personalised account) — skipped without a lookup`,
						);
						continue;
					}
					const rep = await sellerReputation(cand.url);
					const shown = describeReputation(rep);
					if (reputationPasses(rep)) {
						console.log(`    ↑ under the price floor, but the seller clears the bar (${shown}) — allowed`);
						rescued = { product: cand, rep };
						break;
					}
					console.log(
						`    ✗ under the price floor and the seller does not clear ` +
							`${REPUTATION_BAR.rating}★ / ${REPUTATION_BAR.reviews} reviews (${shown}) — skipped`,
					);
				}
			}

			// ⚠️⚠️ **A pair that matched nothing still says what it nearly found.** The
			// suggestion is never written — it carries a `near-miss` reason below, and any
			// reason at all routes a pick to the queue instead of the write path. Without it the
			// pair goes silent, and silence reads as "this shop does not stock it": measured
			// 2026-09-02, `Milk (Fresh) (Skimmed)` searched three terms across 85 Sheng Siong
			// results and said nothing, while Meiji's pasteurized skimmed milk sat in them.
			const suggestions = !rescued && outcome && !outcome.ok ? (outcome.nearMisses ?? []) : [];
			const suggestion = suggestions[0] ?? null;
			if (!rescued && !suggestion && (!outcome || !outcome.ok)) {
				console.log(`    — nothing usable after ${terms.length} search term(s).`);
				continue;
			}

			// ⚠️⚠️ **The runners-up get their own cards.** One suggestion is not enough when a
			// shop stocks siblings: FairPrice lists `Cerave Facial Moisturising Lotion - AM` at
			// $29.90/52ml — the SPF30 this row names, already its recorded price — beside an
			// `AM SPF50` at $30.90, and the SPF50 outranked it. Showing only the top pick hid
			// the right product. Each alternative is a separate card so any one can be accepted.
			//
			// ⚠️ Deliberately BEFORE the main path and deliberately not sharing it: everything
			// below decides whether to WRITE, and an alternative may never be written.
			for (const [k, alt] of suggestions.slice(1).entries()) {
				const altSize = resolveSize(row, alt);
				// Same gate as the write path — a pack this row cannot measure is not offerable.
				if (!altSize) continue;
				const outstandingAlt = findPendingFor(review, row.pageId, route.option, alt);
				if (outstandingAlt?.messageId) continue;
				const altPending: PendingReview = {
					token: outstandingAlt?.token ?? reviewToken(review),
					ingredientId: row.pageId,
					ingredientName: row.name,
					key: cooldownKey(row.target.search.searchTerm),
					unitType: row.unitType,
					vendor: route.option,
					slotN: slot.n,
					brand: row.target.search.brand || undefined,
					priceSgd: alt.priceSgd,
					size: altSize.size,
					url: alt.url,
					itemName: alt.name,
					perLabel: perLabel(row, alt.priceSgd, altSize.size, alt.name),
					reasons: [
						{
							kind: "near-miss",
							note:
								`no product here MATCHED this row — this is alternative ${k + 2} of ` +
								`${suggestions.length}, offered as a suggestion. Accept only if it is the same thing.`,
						},
					],
					askedAt: new Date().toISOString(),
				};
				review = withPending(review, altPending);
				toAsk.push(altPending);
				console.log(
					`    ≋ ${money(alt.priceSgd)} / ${altSize.size}${unitWord(row)}` +
						`\n      ${alt.name}` +
						`\n      ${alt.url}` +
						`\n      ≈ alternative ${k + 2} of ${suggestions.length}, offered as a suggestion`,
				);
			}

			const p = rescued
				? rescued.product
				: (suggestion ?? (outcome as Extract<CandidateOutcome, { ok: true }>).product);
			// ⚠️ One gate for the whole write path — `resolveSize`. A size the shop states
			// always wins; a By Unit row falls back to converting the stated WEIGHT through
			// its own grams-per-unit, which is the only case the row supplies the constant
			// for. The reverse (a counted pack on a weighed row) still has no answer.
			const resolved = resolveSize(row, p);
			if (!resolved) {
				// ⚠️ **A By Unit row that a shop prices by weight is the one refusal the user
				// can fix**, and it is exactly the eggs case the deals page already nudges
				// about (`findWeightGap`). Writing `Stock cubes (120g)` into the Notion name
				// gives the row a grams-per-unit and the conversion above starts working.
				//
				// ⚠️ It fires only on a candidate the matcher ACCEPTED, same discipline as
				// `findWeightGap`: advice to go and retype a Notion row is only worth giving
				// when it will actually work. Razor cartridges and tissue rolls are genuinely
				// countable-only — no shop states a weight, so no candidate ever gets here and
				// no row is nagged about a weight that does not exist.
				const fixable = needsSizeInName(row, p);
				if (fixable) {
					gaps.push({
						name: row.name,
						store: p.store,
						size: p.packWeightG ?? null,
						volumetric: p.volumetric === true,
					});
				}
				console.log(
					`    — refused: "${p.name}" is measured by ${p.unitCount ? "the piece" : "weight"}, ` +
						`but this row is ${row.unitType}` +
						(fixable
							? `.\n      📏 Add a size to the Notion name — e.g. "${row.name.trim()} (${p.packWeightG}${p.volumetric ? "ml" : "g"})" — and this becomes recordable.`
							: `. A scan may not change \`Unit type \`.`),
				);
				refused++;
				continue;
			}

			const size = resolved.size;
			found++;
			// ⚠️ Quoted through `perLabel`, i.e. from what will actually be STORED
			// (`Price [Vendor n]` and `Size[Vendor n]`), not from the product's own
			// `pricePer100g`. On a By-Unit row those two disagree — the slot holds a
			// count — and the report should show the figure Notion will show.
			const per = perLabel(row, p.priceSgd, size, p.name);
			console.log(
				`    ${suggestion ? "≋" : "✓"} ${money(p.priceSgd)} / ${size}${unitWord(row)}` +
					(per ? `  =  ${per}` : "") +
					// The arithmetic in full whenever the count was not the shop's own, so a
					// wrong grams-per-unit is visible in the report rather than only in the
					// price book weeks later.
					(resolved.derived
						? `  ← derived from ${sizeText(p.packWeightG!)} at ${round1(row.gramsPerUnit!)}g each` +
							(resolved.exact ? "" : ` (${round1(p.packWeightG! / row.gramsPerUnit!)}, rounded)`)
						: "") +
					`\n      ${p.name}` +
					`\n      ${p.url}` +
					(p.seller ? `\n      seller: ${p.seller}` : "") +
					// ⚠️ A suggestion is NOT a match, and the report must not let the two look alike.
					// The queue is where it can be accepted; nothing on this path writes it.
					(suggestion
						? `\n      ≈ nothing here matched this row — closest of ${outcome && !outcome.ok ? outcome.considered : 0}, offered as a suggestion`
						: "") +
					// ⚠️ Say it out loud. The figure above is the SHELF price, so a run that sees
					// a 35%-off tag and records the HIGHER number reads as a bug until the report
					// explains itself. See `atShelfPrice`.
					(p.promoPriceSgd != null
						? `\n      🏷️ on promo at ${money(p.promoPriceSgd)} — recording the ${money(p.priceSgd)} shelf price;` +
							` the offer belongs on the deals page`
						: "") +
					// Shown even on an above-floor pick: a normal price from a
					// never-personalised account is not a refusal, but it is worth a look
					// before you hand over money.
					(looksAutoGeneratedHandle(p.seller)
						? `  ⚠️  auto-generated handle — account never personalised`
						: "") +
					(rescued
						? `\n      ⚠️  under the price floor — allowed on seller reputation ` +
							`(${rescued.rep.rating}★, ${rescued.rep.reviews} reviews). Reviews are not ` +
							`product-specific; they say the deal completes, not that the goods are genuine.`
						: "") +
					(!rescued && outcome?.ok && outcome.rejected.length
						? `\n      ⚠️  ${outcome.rejected.length} cheaper listing(s) rejected as implausible` +
							` (the minimum on a marketplace is usually the scam)`
						: "") +
					(outcome?.ok ? `\n      (best of ${outcome.considered} matching)` : ""),
			);

			// ⚠️ **The uncertainty gate, and it sits BEFORE the write on purpose.** Every
			// pick above this line has already passed the matcher and the price rules; the
			// question here is a different one — *is this the pack you would actually
			// buy?* — and it is not one a scan can answer. See `vendor-review.ts`.
			// ⚠️⚠️ **The cheaper-only rule, FIRST in the list on purpose** — it is the
			// headline on the review card, and the only reason here that describes a
			// regression rather than a doubt. See `dearerThanRecorded`.
			//
			// ⚠️ It compares against `slot`, the slot about to be written, which is the
			// one comparison nothing else in this file makes: `referencePer100g` below
			// deliberately excludes it.
			const dearerNow = dearerThanRecorded({
				vendor: route.option,
				recordedPer1000: pricePer1000(slot.priceValue, slot.sizeValue),
				foundPer1000: pricePer1000(p.priceSgd, size),
				// ⚠️ Price AND size, not the per-kilo label: on a By-Unit row those two can
				// agree while the pack changes underneath them. See `dearerThanRecorded`.
				recordedText: priceSizeText(row, slot.priceValue, slot.sizeValue),
				foundText: priceSizeText(row, p.priceSgd, size),
				perWord: perWord(row),
			});

			const reasons: ReviewReason[] = reviewReasons(p, {
				packGrams: packWeightOf(row.unitType, size, row.name, p.name),
				// ⚠️ A pack inside a ceiling the user typed themselves is not a pack to ask
				// them about. Without this the three whey rows (ceiling 10 kg, real packs
				// 2.5 kg) would clear the filter and then be queued anyway by `BULK_GRAMS`,
				// which is 2 kg — asking a question already answered in Notion, every run.
				sizeCeilingOk: row.sizeCeiling != null && packWithinCeiling(row, p),
				referencePer100g: referencePer100g(row.slots, slot.n, row),
				rescued: !!rescued,
				rejectedCheaper: !rescued && outcome?.ok ? outcome.rejected.length : 0,
				autoHandle: looksAutoGeneratedHandle(p.seller),
			});
			if (dearerNow) reasons.unshift(dearerNow);
			// ⚠️ First in the list, because it changes what every other line means: these are
			// facts about a product the matcher did NOT accept.
			if (suggestion)
				reasons.unshift({
					kind: "near-miss",
					note:
						suggestions.length > 1
							? `no product here MATCHED this row — this is the closest of ${suggestions.length} ` +
								"offered, best first. Accept only if it is the same thing."
							: "no product here MATCHED this row — this is the closest one, offered as a suggestion. " +
								"Accept only if it is the same thing.",
				});

			if (reasons.length) {
				// Already asked and still waiting? Say nothing — see `findPendingFor`.
				const outstanding = findPendingFor(review, row.pageId, route.option, p);
				if (outstanding?.messageId) {
					console.log(`      ？ already asked on Telegram — still waiting on your answer.`);
					continue;
				}
				const pending: PendingReview = {
					token: outstanding?.token ?? reviewToken(review),
					ingredientId: row.pageId,
					ingredientName: row.name,
					key: cooldownKey(row.target.search.searchTerm),
					unitType: row.unitType,
					vendor: route.option,
					slotN: slot.n,
					// From `parseName`, so the page offers "Wrong brand" only where a
					// bracketed brand actually exists to enforce.
					brand: row.target.search.brand || undefined,
					priceSgd: p.priceSgd,
					size: size!,
					url: p.url,
					itemName: p.name,
					perLabel: per,
					reasons,
					askedAt: new Date().toISOString(),
				};
				// Queued into the live file immediately so the token it holds is reserved
				// against the next `reviewToken` call in this same loop.
				review = withPending(review, pending);
				toAsk.push(pending);
				console.log(
					`      ？ not written — asking you first:\n` +
						reasons.map((r) => `        ⚠️  ${r.note}`).join("\n"),
				);
				continue;
			}

			/**
			 * Record whether this pick actually MOVES the recorded price, for the morning
			 * message. A rewrite at the same price is reassurance, not news — see
			 * `renderPriceMoves`.
			 *
			 * ⚠️ `slot` holds the PRE-write values: `row.slots` was read before the scan and
			 * `recordVendorPrice` writes to Notion, not to it.
			 */
			const notePriceMove = () => {
				const was = pricePer1000(slot.priceValue, slot.sizeValue);
				const now = pricePer1000(p.priceSgd, size);
				if (now != null && (was == null || now < was)) {
					moves.push({
						row: row.name,
						vendor: route.option,
						recordedText: priceSizeText(row, slot.priceValue, slot.sizeValue),
						foundText: priceSizeText(row, p.priceSgd, size),
						recordedPer1000: was,
						foundPer1000: now,
						perWord: perWord(row),
					});
				} else {
					reconfirmed++;
				}
			};

			if (!doWrite) {
				console.log(`      → would record into ${slot.vendor}. Re-run with --write.`);
				// ⚠️ Collected on the report-only path too, so `npm run vendor-scan` with no
				// flags PREVIEWS the morning message. This file's whole posture is that the
				// report shows exactly what a real run would do; a notification the user
				// cannot see until it arrives on their phone would break that promise.
				notePriceMove();
				continue;
			}

			try {
				const res = await recordVendorPrice(client, row.pageId, {
					vendor: route.option,
					priceSgd: p.priceSgd,
					size,
					url: p.url,
					itemName: p.name,
				});
				const landed = res.slot != null && res.slot.kind !== "none";
				// ⚠️ The test is the SLOT decision, never "were any properties sent" — a
				// button that reports a write it did not make is worse than one that fails
				// loudly (live bug, 2026-08-09).
				if (landed) {
					written++;
					console.log(`      ✔ written — ${res.written.join(", ")}`);
					// ⚠️ **A write is not news; a CHANGE is.** Only counted once the slot
					// actually landed — a refused write must not report a price cut that
					// never happened.
					notePriceMove();
					// ⚠️ **A question answered by WRITING must leave the queue.** Otherwise the
					// review page goes on asking about a price that is already recorded, and
					// tapping OK would re-write it. Live on 2026-08-31: three Carousell picks
					// were queued on a false size-range flag, the flag was fixed, the next run
					// wrote all three into Notion — and all three questions stayed on the page.
					const answered = withoutPendingForSlot(review, row.pageId, route.option);
					if (answered !== review) {
						review = answered;
						questionsDropped++;
						console.log(`      ↩ an outstanding review question is now recorded — dropped.`);
					}
				} else {
					refused++;
					console.log(`      ✗ not written — ${describeSlotDecision(res.slot)}`);
				}
			} catch (e) {
				// One row's failure must not end the batch.
				refused++;
				console.log(`      ✗ write failed — ${(e as Error).message}`);
			}
		}
	}

	await askAboutUncertain(toAsk, review, written, gaps, questionsDropped, moves, reconfirmed);

	console.log(
		`\n${"─".repeat(78)}\n` +
			`${found} candidate(s) found` +
			(doWrite ? `, ${written} written, ${refused} refused/failed` : `, nothing written (no --write)`) +
			(toAsk.length ? `, ${toAsk.length} awaiting your call` : "") +
			(skippedByUser ? `, ${skippedByUser} listing(s) skipped as previously refused` : "") +
			(skippedOverCeiling ? `, ${skippedOverCeiling} over a row's size ceiling` : "") +
			(gaps.length ? `, ${gaps.length} row(s) need a size in their Notion name` : "") +
			".\n",
	);
}

/**
 * Send the review cards and persist the queue.
 *
 * ⚠️ **The file is written even when Telegram fails**, and that order matters. A queued
 * question with no message is recoverable — the next run re-sends it — but a message
 * whose token was never persisted is a button that answers into the void, and the user
 * has no way to tell the two apart from their phone.
 *
 * One card per pick rather than one message listing them all: an inline keyboard belongs
 * to a whole message, so a single message could only carry numbered buttons, and reading
 * "Don't use #7" against a list is exactly how the wrong thing gets refused.
 */
async function askAboutUncertain(
	toAsk: PendingReview[],
	review: Parameters<typeof writeVendorReview>[0],
	written: number,
	gaps: WeightGapNote[],
	/** Questions this run took off the queue by recording the price instead. */
	questionsDropped: number,
	/** Slots whose recorded price actually moved this run. */
	moves: PriceMove[],
	/** Written at the price already recorded — reassurance, not news. */
	reconfirmed: number,
): Promise<void> {
	// ⚠️ **A report-only run writes NOTHING — not Notion, and not this file either.**
	// It has already printed every reason to the console, which is what it was run for.
	// Persisting a queue would make `npm run vendor-scan` with no flags leave state
	// behind, and "report only" has to mean exactly what it says or it stops being the
	// safe thing to reach for.
	/**
	 * ⚠️ **Built once and appended to whatever message goes out, never sent as a second
	 * one.** "One page, one message" is this project's rule and it is what keeps the bot
	 * un-muted; a morning that produced both a question and a price cut should still be
	 * one notification. `null` here means nothing moved — see `renderPriceMoves`.
	 */
	const movesText = renderPriceMoves(moves, reconfirmed, escapeHtml);

	if (!doWrite) {
		if (movesText) console.log(`\nWould report:\n${movesText.replace(/<[^>]+>/g, "")}`);
		if (toAsk.length) console.log(`\n${toAsk.length} pick(s) would be queued for your review.`);
		if (gaps.length) {
			console.log(
				`\n📏 ${gaps.length} row(s) would be flagged as needing a size in the Notion name:\n` +
					gaps
						.map((g) => `   • ${g.name.trim()} — ${g.store} sells these by ${g.volumetric ? "volume" : "weight"}`)
						.join("\n"),
			);
		}
		return;
	}

	// ⚠️ **`questionsDropped` has to open this gate too, or a shrinking queue never reaches the
	// cloud.** `public/` is gitignored and the live page is rebuilt from
	// `data/vendor-review.json` in the repo, so a run that only DROPS questions used to
	// write the local file, return here, and leave the phone showing questions that were
	// already answered. Measured 2026-08-31: 3 written, 0 pushed, 3 still on the page.
	if (!toAsk.length && !questionsDropped) {
		await writeVendorReview(review);
		// ⚠️ Gaps ride along with a message that was being sent anyway — the deals page's
		// rule, and for the same reason: a missing weight is a standing property of the row,
		// true again tomorrow, so a message of its own becomes a nag for a chore already
		// noted. **But this scan is run by hand, not on a schedule**, so with nothing else
		// to say the note would otherwise never be sent at all. Once per manual run is not
		// a nag.
		// ⚠️ **This is the branch the user asked about**: nothing needed their call, but a
		// recorded price may still have MOVED — and until 2026-08-31 that was written into
		// Notion and never mentioned. A daily unattended writer that reports nothing is the
		// silence this project has been bitten by four times.
		// ⚠️ `movesText` is NOT gated on `--no-ask` — see the note on the message block
		// below. A price that moved is news the user asked for; only the question is
		// suppressed. The bare gaps note stays gated, because that one IS a standing nag.
		if (movesText || (gaps.length && !noAsk)) {
			try {
				await sendHtml(movesText ? movesText + formatWeightGaps(gaps) : `🧾 Nothing needed your call.${formatWeightGaps(gaps)}`);
			} catch (e) {
				console.log(`⚠️  Could not send the price-book note (${(e as Error).message}).`);
			}
		}
		return;
	}

	// ⚠️⚠️ **`--no-ask` used to return HERE, and in the cloud that destroys the queue.**
	// It wrote `data/vendor-review.json` and stopped — no page, no commit, no push. On a
	// laptop that is merely useless; on an Actions runner the filesystem goes away, so
	// every uncertain pick is discarded. `daily-vendor-sweep-scope.md` recommends
	// `--write --no-ask` for the cloud sweep, so shipping it that way would have silently
	// lost every question about the 106 cloud-reachable pairs — while reporting success.
	//
	// **`--no-ask` means DO NOT ASK ME, not do not record.** `--no-push` is the flag for
	// not committing, and it is honoured below. So the queue is now published either way
	// and only the Telegram question is suppressed.

	// ⚠️ **One page, one message — never one message per pick.** The first live run
	// queued 16 picks and sent 16 separate cards, which is not a review queue, it is a
	// reason to mute the bot; and a muted bot loses the daily digest with it. The rest of
	// this project has always been "one Telegram message → one page", and so is this.
	await mkdir("public", { recursive: true });
	const page = renderReviewPage(review.pending, { repo: config.repo() });
	await writeFile(REVIEW_PAGE_PATH, page, "utf8");
	console.log(`\nWrote ${REVIEW_PAGE_PATH} (${review.pending.length} waiting).`);

	await writeVendorReview(review);

	// ⚠️ **The queue has to reach the CLOUD or the Telegram link is a lie.** `public/` is
	// gitignored and rebuilt by the daily workflow, so the page written above is a local
	// preview; what the phone opens is built from `data/vendor-review.json` in the repo.
	// Pushing is therefore part of asking, not a separate chore — same shape as the Sheng
	// Siong runner, and the same `commitAndPushData` that survives a rejected push.
	let published = false;
	if (noPush) {
		console.log(`(--no-push: data/vendor-review.json not committed; the live page will not change.)`);
	} else {
		try {
			await commitAndPushData({
				file: "data/vendor-review.json",
				message: `data: ${review.pending.length} price(s) awaiting review`,
			});
			published = true;
		} catch (e) {
			console.log(`⚠️  Could not push the review queue (${(e as Error).message}).`);
		}
	}

	// ⚠️ **A run that only DROPS questions publishes silently.** The page still has to be
	// rebuilt and pushed — that is the whole point of getting here — but there is nothing
	// to ask, and a message saying "0 picks need your call" is a notification that trains
	// the user to ignore the next one that matters. Silent on a clean day; the sweep scope
	// doc asks for the same.
	if (!toAsk.length) {
		console.log(`\n${questionsDropped} stale question(s) dropped — page republished, nothing to ask.`);
		// Still worth a word if a price moved on the same run — the queue shrinking is not
		// itself news, but a cheaper price is. Not gated on `--no-ask`, same reasoning.
		if (movesText) {
			try {
				await sendHtml(movesText + formatWeightGaps(gaps));
			} catch (e) {
				console.log(`⚠️  Could not send the price-book note (${(e as Error).message}).`);
			}
		}
		return;
	}

	/**
	 * ⚠️ **One message, or none — never two.** A morning that produced both a question and
	 * a price cut is still one notification. "One page, one message" is what keeps the bot
	 * un-muted, and a muted bot loses the daily deals digest with it.
	 *
	 * ⚠️ **`--no-ask` silences the QUESTION, not the price news.** The questions are a
	 * standing queue the user visits when they choose — that is what the review page is
	 * for, and it is now published even under `--no-ask`. A price that actually MOVED is
	 * the thing they asked to be told about, and it only fires when something really
	 * changed, so it is not the daily nag `--no-ask` exists to prevent.
	 */
	const parts: string[] = [];
	if (!noAsk) {
		// ⚠️ Only linked when the queue actually reached the repo. A message pointing at a
		// page that still shows yesterday's questions is worse than one that says so.
		parts.push(renderReviewSummary(toAsk.length, written, published ? config.reviewUrl() : undefined));
	}
	if (movesText) parts.push(movesText);

	if (noAsk) {
		console.log(`\n${toAsk.length} pick(s) queued for review — not sent (--no-ask). The page IS published.`);
	}

	if (!parts.length) return;
	try {
		// Gaps appended here rather than inside the pure renderers, which deliberately know
		// nothing about the Telegram client.
		await sendHtml(parts.join("\n\n") + formatWeightGaps(gaps));
		console.log(`📨 Sent one message to Telegram.`);
	} catch (e) {
		console.log(`⚠️  Could not send the message (${(e as Error).message}).`);
		console.log(`   The picks stay queued in data/vendor-review.json; the page is still written.`);
	}
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
