import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { EMPTY_PURCHASES, type PurchaseFile } from "./purchases.js";

/**
 * Where the purchase log lives: `data/purchases.json`, committed to the repo.
 *
 * Same reasoning as `cooldown-file.ts` and `exclusions-file.ts` — the repo is
 * the one store both halves of the system can see. `add-to-list` appends to it,
 * the site build reads it, and the item-actions workflow settles its rows.
 *
 * Unlike the other two, this file only ever GROWS. That is deliberate: it is the
 * system's memory of what a product cost on the day it was bought, and pruning
 * it to keep the file small would throw away the one price record that isn't
 * regenerated by tomorrow's scan.
 */

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const PURCHASES_PATH = join(REPO_ROOT, "data", "purchases.json");

/** Reads the purchase log; a missing or corrupt file is treated as "none yet". */
export async function readPurchases(path = PURCHASES_PATH): Promise<PurchaseFile> {
	try {
		const parsed = JSON.parse(await readFile(path, "utf8"));
		if (!parsed || typeof parsed !== "object") return EMPTY_PURCHASES;
		return {
			version: 1,
			updatedAt: parsed.updatedAt ?? "",
			entries: Array.isArray(parsed.entries) ? parsed.entries : [],
		};
	} catch {
		return EMPTY_PURCHASES; // never let a bad file stop an add or a site build
	}
}

export async function writePurchases(file: PurchaseFile, path = PURCHASES_PATH): Promise<void> {
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, `${JSON.stringify(file, null, 2)}\n`, "utf8");
}
